/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.iths;

import java.sql.SQLException;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;

public class App {
    String sampleStudent = "Ellllinor Ekmark";



    public static void main(String[] args) {
        StudentDAO sDAO = new StudentDAO();
        Collection<Student> students = new HashSet<>();

        try {
            students = sDAO.findAll();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        for (Student student : students) {
            System.out.println(student.toString());
        }


    }





}
